=== Farfetch/garment/core/workspace/schemas/config.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "definitions": {
    "Config": {
      "type": "object",
      "properties": {
        "$schema": {
          "type": "string"
        },
        "presets": {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "properties": {
              "extends": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                ]
              },
              "tasks": {
                "type": "object",
                "additionalProperties": {
                  "$ref": "#/definitions/TaskConfig"
                }
              }
            },
            "additionalProperties": false
          }
        },
        "projects": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/ProjectConfig"
          }
        },
        "schematics": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "yeomanGenerators": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "cache": {
          "oneOf": [
            {
              "type": "object",
              "properties": {
                "type": { "const": "file" },
                "cacheDir": { "type": "string" }
              },
              "additionalProperties": false
            },
            {
              "type": "object",
              "properties": {
                "type": { "const": "remote" }
              },
              "additionalProperties": false
            },
            {
              "type": "object",
              "properties": {
                "type": { "const": "custom" },
                "provider": { "type": "string" }
              },
              "required": ["provider"],
              "additionalProperties": false
            }
          ]
        },
        "experimentalCacheSubscriptions": {
          "type": "boolean"
        }
      },
      "required": ["projects"],
      "additionalProperties": false
    },
    "TaskDefinition": {
      "oneOf": [
        { "type": "string" },
        {
          "type": "object",
          "properties": {
            "runner": {
              "type": "string"
            },
            "skipWatch": {
              "type": "boolean"
            },
            "buildDependencies": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "string"
                },
                {
                  "type": "object",
                  "properties": {
                    "task": { "type": "string" },
                    "watch": { "type": "boolean" }
                  },
                  "required": ["task"],
                  "additionalProperties": false
                }
              ]
            },
            "pipe": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "enum": [true]
                }
              ]
            },
            "input": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "object",
                  "properties": {
                    "rootDir": {
                      "type": "string"
                    },
                    "include": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "exclude": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  },
                  "additionalProperties": false
                },
                {
                  "type": "object",
                  "properties": {
                    "type": { "const": "custom" },
                    "provider": {
                      "type": "string"
                    }
                  },
                  "required": ["type", "provider"],
                  "additionalProperties": false
                }
              ]
            },
            "output": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              ]
            },
            "outputMode": {
              "enum": ["after-all", "after-each", "in-memory"]
            },
            "options": {
              "type": "object",
              "additionalProperties": true
            },
            "env": {
              "additionalProperties": {
                "anyOf": [{ "type": "object" }, { "type": "string" }]
              }
            },
            "next": { "$ref": "#/definitions/TaskConfig" }
          },
          "required": ["runner"],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "parallel": { "$ref": "#/definitions/TaskConfig" },
            "next": { "$ref": "#/definitions/TaskConfig" }
          },
          "required": ["parallel"],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "ref": {
              "type": "string"
            },
            "next": { "$ref": "#/definitions/TaskConfig" }
          },
          "required": ["ref"],
          "additionalProperties": false
        }
      ]
    },
    "TaskConfig": {
      "anyOf": [
        {
          "$ref": "#/definitions/TaskDefinition"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TaskDefinition"
          }
        },
        {
          "enum": [false]
        }
      ]
    },
    "ProjectConfig": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string"
        },
        "extends": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ]
        },
        "dependencies": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "tasks": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/TaskConfig"
          }
        }
      },
      "required": ["path"],
      "additionalProperties": false
    }
  },
  "$ref": "#/definitions/Config"
}

=== Farfetch/garment/garment.json
{
  "$schema": "./packages/workspace/schemas/config.schema.json",
  "presets": {
    "publishable": {
      "tasks": {
        "publish": {
          "runner": "publish",
          "options": {
            "npmrc": ".npmrc"
          }
        },
        "publish:next": {
          "runner": "publish",
          "options": {
            "tag": "next"
          }
        },
        "pack": {
          "runner": "bin",
          "options": {
            "args": "npm pack"
          }
        }
      }
    },
    "runner-preset": {
      "tasks": {
        "docs": {
          "runner": "@garment/runner-docs",
          "output": "{{projectDir}}",
          "options": {
            "template": "packages/runner-docs/template.md"
          }
        },
        "docs-local": {
          "runner": "@garment/runner-docs",
          "output": "{{projectDir}}",
          "options": {
            "template": "{{projectDir}}/README.md"
          }
        }
      }
    },
    "tspackage": {
      "extends": "publishable",
      "tasks": {
        "clean": {
          "runner": "clean",
          "input": "{{projectDir}}/lib/**/*"
        },
        "test": {
          "runner": "jest",
          "buildDependencies": true,
          "options": {
            "configFile": "jest.config.js"
          }
        },
        "go": {
          "runner": "void",
          "input": "{{projectDir}}/src/**/*.*",
          "output": "{{projectDir}}/lib/void",
          "buildDependencies": {
            "task": "go"
          },
          "options": {
            "delay": 10
          }
        },
        "build": {
          "runner": "ts",
          "input": "{{projectDir}}/src/**/*.ts?(x)",
          "output": [
            "{{projectDir}}/lib"
          ],
          "buildDependencies": true,
          "options": {
            "configFile": "tsconfig.base.json"
          }
        }
      }
    },
    "copy-other-files": {
      "tasks": {
        "copy": {
          "runner": "copy",
          "output": "{{projectDir}}/lib",
          "input": {
            "rootDir": "{{projectDir}}/src",
            "exclude": [
              "**/*.ts",
              "**/*.tsx",
              "**/*.js"
            ]
          }
        },
        "postbuild": ":copy"
      }
    },
    "generate-schema": {
      "tasks": {
        "generate-schema": {
          "runner": "typescript-json-schema",
          "input": "{{projectDir}}/src/**/index.ts",
          "output": [
            "{{projectDir}}/lib",
            "{{projectDir}}/src"
          ],
          "options": {
            "pattern": "*Options"
          }
        },
        "build": {
          "ref": "tspackage:build",
          "next": ":generate-schema"
        }
      }
    }
  },
  "projects": {
    "cli": {
      "path": "packages/cli",
      "extends": [
        "tspackage"
      ],
      "tasks": {
        "test": {
          "ref": "tspackage:build",
          "next": "tspackage:test"
        }
      }
    },
    "dependency-graph": {
      "path": "packages/dependency-graph",
      "extends": [
        "tspackage"
      ]
    },
    "garment": {
      "path": "packages/garment",
      "extends": [
        "tspackage"
      ]
    },
    "logger": {
      "path": "packages/logger",
      "extends": [
        "tspackage"
      ]
    },
    "runner": {
      "path": "packages/runner",
      "extends": [
        "tspackage"
      ]
    },
    "scheduler": {
      "path": "packages/scheduler",
      "extends": [
        "tspackage"
      ]
    },
    "schematics-client": {
      "path": "packages/schematics-client",
      "extends": [
        "tspackage"
      ]
    },
    "watcher": {
      "path": "packages/watcher",
      "extends": [
        "tspackage"
      ]
    },
    "workspace": {
      "path": "packages/workspace",
      "extends": [
        "tspackage"
      ]
    },
    "yeoman-client": {
      "path": "packages/yeoman-client",
      "extends": [
        "tspackage"
      ]
    },
    "runner-babel": {
      "path": "packages/plugin-runner-babel",
      "extends": [
        "tspackage",
        "runner-preset",
        "generate-schema"
      ]
    },
    "runner-bin": {
      "path": "packages/plugin-runner-bin",
      "extends": [
        "tspackage",
        "runner-preset",
        "generate-schema"
      ]
    },
    "runner-clean": {
      "path": "packages/plugin-runner-clean",
      "extends": [
        "tspackage",
        "runner-preset"
      ]
    },
    "runner-copy": {
      "path": "packages/plugin-runner-copy",
      "extends": [
        "tspackage",
        "runner-preset"
      ]
    },
    "runner-eslint": {
      "path": "packages/plugin-runner-eslint",
      "extends": [
        "tspackage",
        "runner-preset",
        "generate-schema"
      ]
    },
    "runner-jest": {
      "path": "packages/plugin-runner-jest",
      "extends": [
        "tspackage",
        "runner-preset",
        "generate-schema"
      ]
    },
    "runner-lighthouse": {
      "path": "packages/plugin-runner-lighthouse",
      "extends": [
        "tspackage",
        "runner-preset",
        "generate-schema"
      ]
    },
    "runner-next": {
      "path": "packages/plugin-runner-next",
      "extends": [
        "tspackage",
        "runner-preset",
        "generate-schema"
      ]
    },
    "runner-postcss": {
      "path": "packages/plugin-runner-postcss",
      "extends": [
        "tspackage",
        "runner-preset",
        "generate-schema"
      ]
    },
    "runner-publish": {
      "path": "packages/plugin-runner-publish",
      "extends": [
        "tspackage",
        "runner-preset",
        "generate-schema"
      ]
    },
    "runner-serve": {
      "path": "packages/plugin-runner-serve",
      "extends": [
        "tspackage",
        "runner-preset",
        "generate-schema"
      ]
    },
    "runner-storybook": {
      "path": "packages/plugin-runner-storybook",
      "extends": [
        "tspackage",
        "runner-preset",
        "generate-schema"
      ],
      "tasks": {
        "docs": "runner-preset:docs-local"
      }
    },
    "runner-stylelint": {
      "path": "packages/plugin-runner-stylelint",
      "extends": [
        "tspackage",
        "runner-preset",
        "generate-schema"
      ]
    },
    "runner-ts": {
      "path": "packages/plugin-runner-ts",
      "extends": [
        "tspackage",
        "runner-preset",
        "generate-schema"
      ]
    },
    "runner-typed-css-modules": {
      "path": "packages/plugin-runner-typed-css-modules",
      "extends": [
        "tspackage",
        "runner-preset"
      ],
      "tasks": {
        "docs": "runner-preset:docs-local"
      }
    },
    "runner-typescript-json-schema": {
      "path": "packages/plugin-runner-typescript-json-schema",
      "extends": [
        "tspackage",
        "runner"
      ],
      "tasks": {
        "docs": "runner-preset:docs-local"
      }
    },
    "runner-void": {
      "path": "packages/plugin-runner-void",
      "extends": [
        "tspackage",
        "generate-schema"
      ]
    },
    "runner-wdio": {
      "path": "packages/plugin-runner-wdio",
      "extends": [
        "tspackage",
        "generate-schema"
      ]
    },
    "runner-docs": {
      "path": "packages/plugin-runner-docs",
      "extends": [
        "tspackage"
      ]
    },
    "runner-prettier": {
        "path": "packages/plugin-runner-prettier",
        "extends": [
          "tspackage",
          "runner-preset",
          "generate-schema"
        ]
    },
    "schematics": {
      "path": "packages/schematics",
      "extends": [
        "tspackage",
        "copy-other-files"
      ]
    },
    "schematics-init": {
      "path": "packages/schematics-init",
      "extends": [
        "tspackage"
      ]
    },
    "schematics-typescript": {
      "path": "packages/schematics-typescript",
      "extends": [
        "tspackage",
        "copy-other-files"
      ]
    },
    "schematics-utils": {
      "path": "packages/schematics-utils",
      "extends": [
        "tspackage"
      ]
    },
    "fixture-helper": {
      "path": "packages/fixture-helper",
      "extends": [
        "tspackage"
      ]
    },
    "perf": {
      "path": "packages/perf",
      "extends": [
        "tspackage"
      ]
    },
    "print-tree": {
      "path": "packages/print-tree",
      "extends": [
        "tspackage"
      ]
    },
    "schema-validator": {
      "path": "packages/schema-validator",
      "extends": [
        "tspackage"
      ]
    },
    "visualize-graph": {
      "path": "packages/visualize-graph",
      "extends": [
        "tspackage"
      ]
    },
    "utils": {
      "path": "packages/utils",
      "extends": [
        "tspackage"
      ]
    }
  },
  "schematics": [
    "@garment/schematics",
    "@garment/schematics-typescript"
  ],
  "experimentalCacheSubscriptions": true
}
